/* Dados do lÃ©xico â€” mÃ³dulo TS dentro de src/ para evitar chunks webpack quebrados */
import type { LexiconEntry } from "./types";
import { LEXICON_FAQ_BY_TERM } from "@/data/mock/lexicon";

const BASE_LEXICON: LexiconEntry[] = [
  {
    term_id: "TERM_001",
    term: "dados pessoais",
    aliases: ["dado pessoal", "informaÃ§Ãµes pessoais", "informaÃ§Ã£o pessoal"],
    category: "data_collection",
    meaning: "Qualquer informaÃ§Ã£o que identifique ou possa identificar uma pessoa, como nome, e-mail, CPF, endereÃ§o IP ou localizaÃ§Ã£o.",
    why_it_matters: "Plataformas coletam esses dados para personalizar serviÃ§os, direcionar anÃºncios e compartilhar com parceiros. Saber quais dados sÃ£o coletados Ã© o primeiro passo para proteger sua privacidade.",
    what_you_can_do: "VocÃª pode solicitar ao controlador a lista completa dos seus dados pessoais tratados (Art. 18, II LGPD). TambÃ©m pode pedir a correÃ§Ã£o ou exclusÃ£o.",
    impact: "high",
    icon_id: "user-circle",
    lgpd_refs: ["Art. 5Â°, I", "Art. 18, II"],
  },
  {
    term_id: "TERM_002",
    term: "consentimento",
    aliases: ["autorizaÃ§Ã£o", "concordÃ¢ncia", "aceite"],
    category: "user_rights",
    meaning: "ManifestaÃ§Ã£o livre, informada e inequÃ­voca pela qual o titular concorda com o tratamento de seus dados pessoais para uma finalidade determinada.",
    why_it_matters: "Sem consentimento vÃ¡lido, o tratamento de dados pode ser ilegal. Muitas plataformas utilizam o 'aceite' nos termos como forma de obter esse consentimento de forma ampla.",
    what_you_can_do: "VocÃª pode revogar seu consentimento a qualquer momento, de forma gratuita e facilitada (Art. 8Â°, Â§5Â° LGPD).",
    impact: "high",
    icon_id: "check-circle",
    lgpd_refs: ["Art. 5Â°, XII", "Art. 7Â°, I", "Art. 8Â°"],
  },
  {
    term_id: "TERM_003",
    term: "cookies",
    aliases: ["cookie", "rastreadores", "trackers"],
    category: "data_collection",
    meaning: "Pequenos arquivos armazenados no seu dispositivo que registram informaÃ§Ãµes sobre sua navegaÃ§Ã£o, preferÃªncias e comportamento online.",
    why_it_matters: "Cookies permitem rastrear seus hÃ¡bitos em diferentes sites, criando perfis detalhados para publicidade direcionada, muitas vezes sem que vocÃª perceba.",
    what_you_can_do: "VocÃª pode configurar seu navegador para bloquear cookies de terceiros e usar as ferramentas de gerÃªncia de cookies oferecidas pela plataforma.",
    impact: "medium",
    icon_id: "cookie",
    lgpd_refs: ["Art. 7Â°, I", "Art. 8Â°"],
  },
  {
    term_id: "TERM_004",
    term: "tratamento de dados",
    aliases: ["tratamento", "processamento de dados", "processar dados", "tratar dados"],
    category: "purpose_use",
    meaning: "Toda operaÃ§Ã£o realizada com dados pessoais: coleta, armazenamento, uso, compartilhamento, exclusÃ£o e qualquer outra forma de manipulaÃ§Ã£o.",
    why_it_matters: "O termo Ã© amplo de propÃ³sito. Qualquer coisa que a plataforma faÃ§a com seus dados Ã© 'tratamento'. Por isso, os termos de serviÃ§o devem detalhar cada tipo de operaÃ§Ã£o.",
    what_you_can_do: "VocÃª tem direito a saber exatamente quais tratamentos sÃ£o realizados com seus dados e para quais finalidades (Art. 9Â° LGPD).",
    impact: "high",
    icon_id: "settings",
    lgpd_refs: ["Art. 5Â°, X", "Art. 9Â°"],
  },
  {
    term_id: "TERM_005",
    term: "controlador",
    aliases: ["responsÃ¡vel pelo tratamento"],
    category: "user_rights",
    meaning: "A empresa ou pessoa que toma as decisÃµes sobre o tratamento dos dados pessoais. No caso das redes sociais, Ã© a prÃ³pria plataforma (Meta, X Corp.).",
    why_it_matters: "Ã‰ ao controlador que vocÃª deve dirigir solicitaÃ§Ãµes de acesso, correÃ§Ã£o ou exclusÃ£o de dados. Saber quem Ã© o controlador Ã© essencial para exercer seus direitos.",
    what_you_can_do: "VocÃª pode contatar o controlador (geralmente via DPO/Encarregado) para exercer qualquer direito previsto no Art. 18 da LGPD.",
    impact: "medium",
    icon_id: "building",
    lgpd_refs: ["Art. 5Â°, VI", "Art. 18"],
  },
  {
    term_id: "TERM_006",
    term: "compartilhamento",
    aliases: ["compartilhar", "compartilhamento de dados", "transferÃªncia de dados", "ceder dados", "repasse"],
    category: "sharing_third_parties",
    meaning: "ComunicaÃ§Ã£o, transferÃªncia ou disponibilizaÃ§Ã£o de dados pessoais a terceiros, como parceiros comerciais, anunciantes ou autoridades.",
    why_it_matters: "Quando seus dados sÃ£o compartilhados, eles saem do controle direto da plataforma original. VocÃª pode nÃ£o saber quem tem acesso nem como serÃ£o usados.",
    what_you_can_do: "VocÃª pode solicitar informaÃ§Ãµes sobre com quem seus dados sÃ£o compartilhados (Art. 18, VII LGPD).",
    impact: "high",
    icon_id: "share-2",
    lgpd_refs: ["Art. 5Â°, XVI", "Art. 18, VII"],
  },
  {
    term_id: "TERM_007",
    term: "terceiros",
    aliases: ["parceiros", "parceiros comerciais", "empresas parceiras", "third parties"],
    category: "sharing_third_parties",
    meaning: "Empresas ou entidades externas Ã  plataforma que podem receber ou acessar seus dados, como anunciantes, provedores de analytics ou parceiros de negÃ³cios.",
    why_it_matters: "Os termos frequentemente listam categorias vagas de 'terceiros'. Entender quem sÃ£o esses parceiros ajuda a avaliar o risco real Ã  sua privacidade.",
    what_you_can_do: "Exija transparÃªncia: peÃ§a Ã  plataforma a lista de terceiros com quem seus dados sÃ£o compartilhados.",
    impact: "high",
    icon_id: "users",
    lgpd_refs: ["Art. 18, VII"],
  },
  {
    term_id: "TERM_008",
    term: "finalidade",
    aliases: ["propÃ³sito", "objetivo do tratamento", "para que"],
    category: "purpose_use",
    meaning: "O motivo especÃ­fico pelo qual seus dados sÃ£o coletados e tratados. A LGPD exige que toda coleta tenha uma finalidade legÃ­tima, especÃ­fica e informada ao titular.",
    why_it_matters: "Se a plataforma usa seus dados para um propÃ³sito diferente do informado, isso pode configurar violaÃ§Ã£o da LGPD. Finalidades vagas como 'melhorar a experiÃªncia' sÃ£o um sinal de alerta.",
    what_you_can_do: "VocÃª pode questionar finalidades genÃ©ricas e solicitar detalhamento. Caso seus dados sejam usados para fim diferente do consentido, pode denunciar Ã  ANPD.",
    impact: "high",
    icon_id: "target",
    lgpd_refs: ["Art. 6Â°, I", "Art. 9Â°"],
  },
  {
    term_id: "TERM_009",
    term: "retenÃ§Ã£o",
    aliases: ["armazenamento", "prazo de armazenamento", "guardar dados", "manter dados", "perÃ­odo de retenÃ§Ã£o"],
    category: "retention_storage",
    meaning: "O perÃ­odo pelo qual a plataforma mantÃ©m seus dados armazenados, mesmo apÃ³s vocÃª parar de usar o serviÃ§o.",
    why_it_matters: "Muitas plataformas retÃªm dados por anos, mesmo apÃ³s exclusÃ£o da conta. Saber o prazo de retenÃ§Ã£o ajuda a entender por quanto tempo seus dados ficam expostos.",
    what_you_can_do: "VocÃª pode solicitar a eliminaÃ§Ã£o dos dados apÃ³s o tÃ©rmino do tratamento (Art. 16 LGPD), salvo obrigaÃ§Ãµes legais de guarda.",
    impact: "medium",
    icon_id: "clock",
    lgpd_refs: ["Art. 15", "Art. 16"],
  },
  {
    term_id: "TERM_010",
    term: "anonimizaÃ§Ã£o",
    aliases: ["anonimizar", "dados anonimizados", "dados anÃ´nimos"],
    category: "retention_storage",
    meaning: "Processo tÃ©cnico pelo qual um dado perde a possibilidade de ser associado a uma pessoa especÃ­fica, de forma irreversÃ­vel.",
    why_it_matters: "Dados verdadeiramente anonimizados nÃ£o sÃ£o considerados dados pessoais pela LGPD. PorÃ©m, muitas tÃ©cnicas de 'anonimizaÃ§Ã£o' sÃ£o reversÃ­veis (pseudonimizaÃ§Ã£o), e a plataforma pode usar esse termo de forma imprecisa.",
    what_you_can_do: "Questione se o processo Ã© realmente irreversÃ­vel. Dados pseudonimizados ainda sÃ£o dados pessoais e mantÃªm todos os seus direitos LGPD.",
    impact: "medium",
    icon_id: "eye-off",
    lgpd_refs: ["Art. 5Â°, III", "Art. 12"],
  },
  {
    term_id: "TERM_011",
    term: "incidente de seguranÃ§a",
    aliases: ["vazamento", "violaÃ§Ã£o de dados", "brecha de seguranÃ§a", "data breach"],
    category: "security_incidents",
    meaning: "Qualquer evento que comprometa a confidencialidade, integridade ou disponibilidade de dados pessoais, como vazamentos, acessos nÃ£o autorizados ou perda de dados.",
    why_it_matters: "Incidentes podem expor dados sensÃ­veis a criminosos. A LGPD obriga o controlador a comunicar incidentes graves Ã  ANPD e aos titulares afetados.",
    what_you_can_do: "Caso saiba de um incidente envolvendo seus dados, cobre transparÃªncia da plataforma e monitore suas contas. VocÃª pode denunciar Ã  ANPD se a empresa nÃ£o comunicar o incidente.",
    impact: "high",
    icon_id: "alert-triangle",
    lgpd_refs: ["Art. 48"],
  },
  {
    term_id: "TERM_012",
    term: "titular",
    aliases: ["titular dos dados", "usuÃ¡rio", "sujeito dos dados"],
    category: "user_rights",
    meaning: "A pessoa natural a quem os dados pessoais se referem. Se vocÃª usa a plataforma, vocÃª Ã© o titular dos dados que ela coleta.",
    why_it_matters: "A LGPD confere ao titular uma sÃ©rie de direitos (Art. 18), como acesso, correÃ§Ã£o, exclusÃ£o e portabilidade. Saber que vocÃª Ã© o titular Ã© o ponto de partida para exercÃª-los.",
    what_you_can_do: "ExerÃ§a seus direitos: solicite acesso, correÃ§Ã£o, exclusÃ£o ou portabilidade dos seus dados diretamente Ã  plataforma (Art. 18 LGPD).",
    impact: "high",
    icon_id: "user",
    lgpd_refs: ["Art. 5Â°, V", "Art. 17", "Art. 18"],
  },
];

export const LEXICON: LexiconEntry[] = BASE_LEXICON.map((entry) => ({
  ...entry,
  faqs: LEXICON_FAQ_BY_TERM[entry.term_id],
}));


