import type { PaperGroup } from "@/document_engine/types";

export const DOCUMENT_REPOSITORY: PaperGroup[] = [
  {
    id: "x-twitter",
    label: "X / Twitter",
    hint: "Termos e privacidade da plataforma X.",
    accent: "#1d4ed8",
    brandMark: "X",
    brandLabel: "Marca textual X",
    documents: [
      {
        id: "X_TERMS",
        title: "X Terms of Service",
        content: "",
        source: "X",
        kind: "terms",
        locale: "pt-BR",
        stamp: "2026-04-21T19:45:49.284Z",
        link: "https://x.com/pt/tos",
        groupId: "x-twitter",
        description: "Termos contratuais de uso, conta, conteudo e aplicacao de regras.",
      },
      {
        id: "X_PRIVACY",
        title: "X Privacy Policy",
        content: "",
        source: "X",
        kind: "privacy",
        locale: "pt-BR",
        stamp: "2026-04-21T19:45:49.284Z",
        link: "https://x.com/pt/privacy",
        groupId: "x-twitter",
        description: "Politica de privacidade sobre coleta, uso e compartilhamento de dados.",
      },
    ],
  },
  {
    id: "meta-facebook",
    label: "Meta / Facebook",
    hint: "Fontes oficiais da Meta para Facebook.",
    accent: "#2563eb",
    brandMark: "Meta",
    brandLabel: "Marca textual Meta",
    documents: [
      {
        id: "META_TERMS",
        title: "Meta/Facebook Terms of Service",
        content: "",
        source: "Meta/Facebook",
        kind: "terms",
        locale: "pt-BR",
        stamp: "2026-04-21T19:45:49.284Z",
        link: "https://www.facebook.com/terms/?locale=pt_BR",
        groupId: "meta-facebook",
        description: "Termos de uso do Facebook, licencas, suspensao e governanca da conta.",
      },
      {
        id: "META_PRIVACY",
        title: "Meta Privacy Policy",
        content: "",
        source: "Meta/Facebook",
        kind: "privacy",
        locale: "pt-BR",
        stamp: "2026-04-21T19:45:49.284Z",
        link: "https://www.facebook.com/privacy/policy/?locale=pt_BR",
        groupId: "meta-facebook",
        description: "Politica de privacidade da Meta para produtos e servicos conectados.",
      },
    ],
  },
  {
    id: "instagram",
    label: "Instagram",
    hint: "Termos e privacidade do ecossistema Instagram.",
    accent: "#c026d3",
    brandMark: "IG",
    brandLabel: "Marca textual Instagram",
    documents: [
      {
        id: "INSTAGRAM_TERMS",
        title: "Instagram Terms of Use",
        content: "",
        source: "Instagram",
        kind: "terms",
        locale: "pt-BR",
        stamp: "2026-04-21T19:45:49.284Z",
        link: "https://help.instagram.com/581066165581870/?locale=pt_BR",
        groupId: "instagram",
        description: "Termos de uso aplicaveis ao uso do Instagram.",
      },
      {
        id: "INSTAGRAM_PRIVACY",
        title: "Instagram Privacy Policy Reference",
        content: "",
        source: "Instagram/Meta",
        kind: "privacy",
        locale: "auto",
        stamp: "2026-04-21T19:45:49.284Z",
        link: "https://privacycenter.instagram.com/policy",
        groupId: "instagram",
        description: "Referencia oficial de privacidade no centro de privacidade da Meta.",
      },
    ],
  },
  {
    id: "governo-planalto",
    label: "Governo / Planalto",
    hint: "Fonte normativa brasileira para comparacao juridica.",
    accent: "#15803d",
    brandMark: "GOV",
    brandLabel: "Marca textual Governo Federal",
    documents: [
      {
        id: "LGPD_EXCERPTS",
        title: "Lei Geral de Protecao de Dados Pessoais - LGPD",
        content: "",
        source: "Planalto",
        kind: "other",
        locale: "pt-BR",
        stamp: "2026-04-21T20:40:25.913Z",
        link: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/L13709compilado.htm",
        groupId: "governo-planalto",
        description: "Base legal brasileira para direitos, principios e tratamento de dados.",
      },
    ],
  },
];
